{% if SCHEMA_ADMIN %}
CREATE TABLE {{ SCHEMA_ADMIN }}.CHANGELOGS
(
    FILENAME TEXT NOT NULL,
    ORDER_ID INTEGER NOT NULL,
    HASH     TEXT NOT NULL,
    DATEEXEC TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
)
{% else  %}
CREATE TABLE CHANGELOGS
(
    FILENAME TEXT NOT NULL,
    ORDER_ID INTEGER NOT NULL,
    HASH     TEXT NOT NULL,
    DATEEXEC TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
)
{% endif %}
