{% if SCHEMA_ADMIN %}
CREATE TABLE {{ SCHEMA_ADMIN }}.CHANGELOGS
(
    FILENAME VARCHAR(255) NOT NULL,
    ORDER_ID INTEGER NOT NULL,
    HASH     VARCHAR(255) NOT NULL,
    DATEEXEC TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
)
{% else  %}
CREATE TABLE CHANGELOGS
(
    FILENAME VARCHAR(255) NOT NULL,
    ORDER_ID INTEGER NOT NULL,
    HASH     VARCHAR(255) NOT NULL,
    DATEEXEC TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
)
{% endif %}
