{% if SCHEMA_ADMIN %}
CREATE TABLE IF NOT EXISTS {{ SCHEMA_ADMIN }}.CHANGELOGS
(
    FILENAME TEXT NOT NULL,
    ORDER_ID INT  NOT NULL,
    HASH     TEXT NOT NULL,
    DATEEXEC TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
{% else  %}
CREATE TABLE IF NOT EXISTS CHANGELOGS
(
    FILENAME TEXT NOT NULL,
    ORDER_ID INT  NOT NULL,
    HASH     TEXT NOT NULL,
    DATEEXEC TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
{% endif %}
