{% if SCHEMA_ADMIN %}
CREATE TABLE IF NOT EXISTS {{ SCHEMA_ADMIN }}.CHANGELOGS
(
    NAME     TEXT NOT NULL,
    FILENAME TEXT NOT NULL,
    ORDER_ID INT  NOT NULL,
    HASH     TEXT NOT NULL,
    AUTHOR   TEXT,
    DATEEXEC DATE NOT NULL
)
-- <->
{% else  %}
CREATE TABLE IF NOT EXISTS CHANGELOGS
(
    NAME     TEXT NOT NULL,
    FILENAME TEXT NOT NULL,
    ORDER_ID INT  NOT NULL,
    HASH     TEXT NOT NULL,
    AUTHOR   TEXT,
    DATEEXEC DATE NOT NULL
)
-- <->
{% endif %}
