name: Build and testing

on:
  push:
    branches: [ main, realase-*, dependabot/cargo/* ]
  pull_request:
    branches: [ main, realase-*, dependabot/cargo/* ]

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly

      - run: rustup component add rustfmt --toolchain nightly

      - uses: actions-rs/cargo@v1
        with:
          command: +nightly fmt
          args: --verbose --all
#  check:
#    name: Check
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#
#      - uses: hecrj/setup-rust-action@v1
#        with:
#          rust-version: nightly
#
#      -run: rustup component add clippy
#
#
#      - uses: actions-rs/cargo@v1
#        with:
#          command: clippy
#          args: --all-target --all-features

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        rust: [ nightly ]
        features: [ postgres ]

    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}

      - uses: actions/checkout@v2

      - name: Build
        run: cargo build --verbose

      - uses: actions-rs/clippy@master
        with:
          args: --all-features --all-targets

  postgres:
    name: Postgres
    runs-on: ubuntu-latest
    strategy:
      matrix:
        postgres: [latest]
        runtime: [postgres]
    steps:
      - uses: actions/checkout@v2

      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: >
            --no-default-features
            --features postgres

      - run: docker-compose -f .docker/docker-compose.yml run -d -p 5432:5432 postgres_${{ matrix.postgres }}
      - run: sleep 15

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: >
            --no-default-features
            --features postgres
        env:
          DATABASE_URL: postgres://postgres:example@localhost:5432/postgres