name: Build and testing

on:
  push:
    branches: [ main, realase-*, dependabot/cargo/* ]
  pull_request:
    branches: [ main, realase-*, dependabot/cargo/* ]

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - run: rustup component add rustfmt --toolchain nightly

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: +nightly --all --check

  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        rust: [ nightly ]
        features: [ postgres ]

    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}

      - uses: actions/checkout@v2

      - name: Build
        run: cargo build --verbose

      - uses: actions-rs/clippy@master
        with:
          args: --all-features --all-targets
